// AI 情报工作台 - 每日简报数据层（v2.1：9 类目 + 海外标注 + 务实深度池）
// 字段：cat 分类 / time 时间 / title 标题 / summary 摘要 / impact 重要性(high|mid|low)
// related 是否与用户相关(招联×联通专项·家庭财务·育儿) / decision 决策提示
// source 来源 / url 原文链接 / overseas 是否海外信源(true|false)
window.BRIEFING = {
  "date": "2026-08-07",
  "edition": "每日双版 · 早览 + 详报（同源生成）",
  "generatedAt": "2026-08-07 17:25 (v2.1 新增母婴类目)",
  "scope": "中国优先 + 全球要闻（金融 · AI行业 · 母婴 · 政治 · 军事 · 经济 · 科技 · 社会 · 娱乐），海外条目已标注「海外」",
  "kpi": {
    "total": 60,
    "high": 22,
    "related": 21
  },
  "items": [
    {
      "id": 1,
      "cat": "政治/政策",
      "time": "08:30",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "中央政治局会议：宏观政策要“发力提效”",
      "summary": "部署下半年经济工作，实施更积极的财政政策和适度宽松的货币政策，加力扩内需、优化供给；上半年 GDP 同比增长 4.7%，新动能贡献率超四成。",
      "decision": "稳增长加码直接影响消费金融需求与利率环境，与招联主业及家庭信贷成本密切相关，建议持续跟踪政策落地节奏。",
      "source": "新浪财经",
      "url": "https://finance.sina.com.cn/jjxw/2026-08-07/doc-inimnenp3289533.shtml"
    },
    {
      "id": 2,
      "cat": "政治/政策",
      "time": "18:50",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "国常会部署新型电网、物流网建设；央行明确下半年工作重点",
      "summary": "国常会听取新型电网、物流网建设汇报，核准辽宁庄河等四个核电项目；央行下半年工作会议强调继续实施适度宽松的货币政策，保持流动性充裕。",
      "decision": "货币宽松 + 重大基建投资双线发力，利好信用扩张与内需；关注对贷款利率、理财收益的后续传导。",
      "source": "21世纪经济报道",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 3,
      "cat": "政治/政策",
      "time": "09:10",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "商务部发布“产能过剩”问题中方立场文件",
      "summary": "中方直指西方将“产能过剩”包装为政治叙事、为其歧视性贸易限制措施造势，表明开放合作的立场，并阐明内需与出口相互支撑。",
      "decision": "关注中欧/中美经贸摩擦对出口链与汇率的潜在影响，若从事跨境业务需留意关税与合规风险。",
      "source": "腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260807A06ICF00"
    },
    {
      "id": 4,
      "cat": "政治/政策",
      "time": "18:20",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "《出境入境管理规定》9月15日起施行",
      "summary": "规定共19条，旨在规范出境入境管理、保障出境入境人员合法权益、维护国家主权安全发展利益，自2026年9月15日起施行。",
      "decision": "若后续有出境（产检/探亲/旅行）计划，留意新规对签证与通关流程的影响，提前规划。",
      "source": "腾讯新闻",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 5,
      "cat": "政治/政策",
      "time": "18:25",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "智能网联汽车自动驾驶强制国标发布，2027年实施",
      "summary": "《智能网联汽车 自动驾驶系统安全要求》强制性国家标准正式发布，适用于 L3/L4 级系统，拟于2027年7月1日起实施。",
      "decision": "自动驾驶合规提速，关注智能汽车产业链与联通车联网业务的协同机会。",
      "source": "腾讯新闻",
      "url": "https://so.html5.qq.com/page/real/search_news?docid=70000021_9336a726d2426452"
    },
    {
      "id": 6,
      "cat": "军事/地缘",
      "time": "10:38",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "美防部起草新核战略，拟对华俄动用战术核武器",
      "summary": "环球时报援引 NBC 报道，五角大楼正修订核战略，地区战争中将更倚重短程战术核武器；中方专家称属“赤裸裸的核讹诈”。",
      "decision": "地缘风险升温或推升避险情绪、金价与油价波动，影响家庭大类资产配置与出行成本，保持关注。",
      "source": "环球时报",
      "url": "https://finance.sina.cn/2026-08-07/detail-inimnent3192080.d.html"
    },
    {
      "id": 7,
      "cat": "军事/地缘",
      "time": "11:02",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "俄乌与中东战线合流，西方警示“三战风险”",
      "summary": "里海商船遭袭使俄乌与中东两条战线相连；报道称美军拦截弹库存消耗承压，多家分析机构警示冲突边界正在扩大。",
      "decision": "能源与军工供应链扰动可能传导至油价与通胀，留意对日常出行、生活成本的间接影响。",
      "source": "网易",
      "url": "https://www.163.com/dy/article/L3MIQLH2055615MY.html"
    },
    {
      "id": 8,
      "cat": "军事/地缘",
      "time": "18:30",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "国防部回应日本防卫白皮书诬称中国军事挑战",
      "summary": "针对日本新版《防卫白皮书》诬称中国军事动向是“最大战略挑战”，国防部发言人敦促日方深刻反省侵略历史、停止干涉内政。",
      "decision": "周边安全叙事趋紧，关注中日经贸与半导体出口管制动向的连带影响。",
      "source": "腾讯新闻",
      "url": "https://so.html5.qq.com/page/real/search_news?docid=70000021_9336a726d2426452"
    },
    {
      "id": 9,
      "cat": "军事/地缘",
      "time": "19:10",
      "impact": "high",
      "related": false,
      "overseas": true,
      "title": "[海外] Trump's Iran war enters sixth month with no exit in sight",
      "summary": "Reuters：特朗普对伊朗战争已进入第六个月，本周的外交与威胁交织凸显其试图抽身却越陷越深的困局；霍尔木兹海峡风险持续。",
      "decision": "中东局势直接牵动油价与全球避险情绪，关注对国内油价、出行成本及权益资产的传导。",
      "source": "Reuters",
      "url": "https://www.reuters.com"
    },
    {
      "id": 10,
      "cat": "军事/地缘",
      "time": "19:12",
      "impact": "mid",
      "related": false,
      "overseas": true,
      "title": "[海外] Taiwan troops rehearse sealing key bridge during war games",
      "summary": "Reuters：台军在三军演习中演练封锁战略咽喉要道的关键桥梁，区域军事紧张态势延续。",
      "decision": "台海军事活动频次影响区域风险溢价，留意对半导体供应链与汇率的潜在扰动。",
      "source": "Reuters",
      "url": "https://www.reuters.com"
    },
    {
      "id": 11,
      "cat": "军事/地缘",
      "time": "19:14",
      "impact": "mid",
      "related": false,
      "overseas": true,
      "title": "[海外] Ukrainian attacks on Wildberries strike at heart of Russia Inc",
      "summary": "Reuters 卫星图像评估：Wildberries 超五分之一仓储空间受损或摧毁，显示俄乌冲突对俄本土物流与零售体系的持续打击。",
      "decision": "冲突长期化抬升全球物流与通胀不确定性，关注对进口成本与供应链的间接影响。",
      "source": "Reuters",
      "url": "https://www.reuters.com"
    },
    {
      "id": 12,
      "cat": "军事/地缘",
      "time": "18:40",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "中国海军“吉祥方舟”号医院船首次赴海外执行任务",
      "summary": "海军“吉祥方舟”号医院船将赴非洲、南亚执行“和谐使命-2026”任务，彰显远海卫勤与 humanitarian 能力。",
      "decision": "远海行动常态化反映海军建设推进，长期利好船舶与军工产业链。",
      "source": "国防部",
      "url": "http://www.mod.gov.cn:8080/"
    },
    {
      "id": 13,
      "cat": "经济",
      "time": "09:40",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "外资持续看好中国经济，硬科技成成长主线",
      "summary": "多家外资机构认为中国经济展现稳定性与韧性，上半年 GDP +4.7%；新能源、新型储能、创新药及大模型产业链被视为长期投资逻辑。",
      "decision": "科技成长板块与招联×联通“AI 算力”方向共振，可关注相关产业与就业/业务机会。",
      "source": "中国经济网",
      "url": "https://www.ce.cn/xwzx/gnsz/gdxw/202608/t20260807_3134294.shtml"
    },
    {
      "id": 14,
      "cat": "经济",
      "time": "10:00",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "美元周线年内最大跌幅，美元/人民币约 6.75",
      "summary": "美联储新主席“鹰派语言、鸽派行动”引发信誉担忧，美元兑日元单周暴跌 3.6%；美元人民币维持在 6.75 附近。",
      "decision": "人民币偏强利好出境消费与留学，但持有美元资产需关注汇率波动，家庭外汇敞口宜适度。",
      "source": "汇通财经",
      "url": "https://www.fx678.com/C/20260801/202608011326002285.html"
    },
    {
      "id": 15,
      "cat": "经济",
      "time": "18:55",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "央行下半年工作会议：继续实施适度宽松的货币政策",
      "summary": "央行强调综合运用并适时调整货币政策工具，保持流动性充裕，引导金融机构增强信贷投放均衡性，使社融、货币供应同经济增长与价格目标匹配。",
      "decision": "流动性宽松利好消费金融资金端与利率环境，直接关联招联资金成本，建议纳入周报跟踪。",
      "source": "21世纪经济报道",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 16,
      "cat": "经济",
      "time": "19:00",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "外汇局：稳步扩大外汇领域制度型开放，支持跨境电商",
      "summary": "外汇管理工作会议部署下半年重点，提出推动贸易便利化改革，全面推广跨境贸易高水平开放外汇收支便利化政策，支持跨境电商等新业态。",
      "decision": "跨境贸易便利化利好出海与电商产业链，关注对消费金融跨境场景的潜在延伸。",
      "source": "21世纪经济报道",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 17,
      "cat": "经济",
      "time": "18:58",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "国常会核准辽宁庄河等四个核电项目",
      "summary": "会议按照全球最高安全标准核准核电项目，强调压实主体责任、加强全链条安全监管，确保核电安全万无一失。",
      "decision": "核电审批重启利好清洁能源与高端装备投资，关注相关产业链机会。",
      "source": "21世纪经济报道",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 18,
      "cat": "经济",
      "time": "19:02",
      "impact": "low",
      "related": false,
      "overseas": false,
      "title": "财政部：1—6月国有企业利润总额同比增长 2.4%",
      "summary": "财政部公布数据，全国国有及国有控股企业营业总收入同比下降2%，利润总额同比增长2.4%。",
      "decision": "国企利润企稳反映经济韧性，可作权益与固收配置的判断参考之一。",
      "source": "财政部/21世纪",
      "url": "https://www.toutiao.com/article/7669384812230115840"
    },
    {
      "id": 19,
      "cat": "经济",
      "time": "19:20",
      "impact": "mid",
      "related": false,
      "overseas": true,
      "title": "[海外] Oil rises on Mideast risk; Asian shares pause for US jobs",
      "summary": "Reuters：受中东风险与美军行动不确定性影响，油价延续涨势；亚洲股市在等待美国就业数据前观望。",
      "decision": "油价上行叠加海外利率预期波动，影响国内输入性通胀与出行成本，保持关注。",
      "source": "Reuters",
      "url": "https://www.reuters.com"
    },
    {
      "id": 20,
      "cat": "经济",
      "time": "19:22",
      "impact": "mid",
      "related": false,
      "overseas": true,
      "title": "[海外] Trump unveils trade actions to compete with China on solar and chips",
      "summary": "Reuters：美方出台新一轮贸易举措，在太阳能与芯片领域强化对华竞争，全球供应链重组预期升温。",
      "decision": "芯片/光伏贸易壁垒升级，关注对国产替代（半导体、新能源）板块的情绪与实质影响。",
      "source": "Reuters",
      "url": "https://www.reuters.com"
    },
    {
      "id": 21,
      "cat": "科技",
      "time": "10:05",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "中国联通 2026 算力跑出“加速度”",
      "summary": "联通建成全球领先 5G-A 网络，元景 MaaS 汇聚 140+ 模型、万悟智能体平台开源，已推出 200 款 AI 应用，服务超 43.8 万行业客户。",
      "decision": "与你在招联×联通专项高度相关——联通 AI + 算力布局是专项核心抓手，建议重点跟进并纳入周报跟踪。",
      "source": "腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260804A0AGPT00"
    },
    {
      "id": 22,
      "cat": "科技",
      "time": "10:20",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "联通签约世界人形机器人运动会独家通信伙伴",
      "summary": "中国联通成为第二届世界人形机器人运动会全球独家通信服务合作伙伴，并成立具身智能全域通信联合实验室。",
      "decision": "具身智能 + 通信融合是联通新增长点，可列入专项机会清单，关注后续商业化落地。",
      "source": "科技日报",
      "url": "https://www.stdaily.com/web/gdxw/2026-08/05/content_559682.html"
    },
    {
      "id": 23,
      "cat": "科技",
      "time": "11:10",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "中国存储半导体全产业链业绩“井喷”，超八成预喜",
      "summary": "已披露上半年业绩预告的 A 股半导体公司超八成预喜，从存储到封测到设备全面爆发；AI 算力需求推动存储从“周期品”走向“成长主线”。",
      "decision": "半导体景气上行利好硬科技权益资产，关注国产存储与设备链的长期配置价值。",
      "source": "央视网",
      "url": "https://news.cctv.cn/2026/08/02/ARTIdXn1LmRbPyyhzgpZkfnm260802.shtml"
    },
    {
      "id": 24,
      "cat": "科技",
      "time": "12:35",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "长鑫科技登陆科创板登顶 A 股市值榜首",
      "summary": "长鑫实现 DRAM 自主规模化量产，打通设计-制造-封装完整产业链；登陆科创板后市值登顶，被视为全球芯片格局突围标志。",
      "decision": "存储自主可控筑牢算力产业安全底线，关注半导体“强者恒强”分化行情。",
      "source": "今日头条",
      "url": "https://www.toutiao.com/article/7669658771258262068/"
    },
    {
      "id": 25,
      "cat": "科技",
      "time": "08:06",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "燧原科技科创板注册生效，腾讯持股约两成拟募 60 亿",
      "summary": "腾讯持股约两成、三年累亏 43 亿元的燧原科技获科创板注册生效，拟募资 60 亿元，国产 AI 芯片四家头部企业全部进入资本市场。",
      "decision": "国产 AI 芯片资本化加速，关注与腾讯/联通生态的协同及算力自主化主线。",
      "source": "腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260806A07P1700"
    },
    {
      "id": 26,
      "cat": "科技",
      "time": "20:00",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "上海纳米计量获国家科技进步一等奖，补芯片测量短板",
      "summary": "同济牵头、上检计量联合完成的“量子化光晶格常数纳米计量”项目获国家科技进步一等奖，0.001 纳米级精度补齐先进芯片制造测量短板。",
      "decision": "底层计量突破支撑芯片自主可控，长期利好半导体设备与材料国产替代。",
      "source": "上观新闻",
      "url": "https://www.toutiao.com/article/7669774138336903715/"
    },
    {
      "id": 27,
      "cat": "科技",
      "time": "08:05",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "“十五五”新型电力系统路线图出炉，2030 非化石能源发电占比 50%",
      "summary": "发改委、能源局发布新型电力系统建设“十五五”规划，提出到2030年非化石能源发电量占比达50%。",
      "decision": "新能源与电网投资确定性提升，关注储能、特高压与绿电产业链机会。",
      "source": "央广网",
      "url": "https://new.qq.com/rain/a/20260806A07P1700"
    },
    {
      "id": 28,
      "cat": "社会/生活",
      "time": "11:15",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "育儿补贴与带薪休假新政陆续落地",
      "summary": "河南出台带薪休假新政（领导带头休假、未休按 300% 补偿）；多地育儿补贴细则推进，产假与照护支持持续完善。",
      "decision": "宝宝预产期 8/25 临近，育儿补贴、产假休假政策直接利好家庭现金流与时间安排，建议提前核对本地申领条件。",
      "source": "极目新闻",
      "url": "http://view.inews.qq.com/a/20260805A0DRVP00"
    },
    {
      "id": 29,
      "cat": "社会/生活",
      "time": "08:05",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "抗生素牛蛙再现餐桌，超 4 成样品超标，监管下架",
      "summary": "媒体曝电商牛蛙样品超 4 成抗生素超标、检出禁用物质，漳州汕头等地封存送检、平台下架，监管前移呼声高涨。",
      "decision": "家中有孕晚期及新生儿，食材安全需格外留意，采购走正规渠道、去皮去内脏、充分加热。",
      "source": "封面新闻",
      "url": "https://new.qq.com/rain/a/20260806A07P1700"
    },
    {
      "id": 30,
      "cat": "社会/生活",
      "time": "18:35",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "百日千万招聘专项行动推出 AI/新能源等 4 专场，需求 21.5 万",
      "summary": "8月3日至9日，百日千万招聘专项行动推出人工智能、新能源、医疗卫生、物流行业 4 个线上招聘专场，1700 多家用人单位参与。",
      "decision": "AI/新能源招聘需求旺盛，反映结构性就业风向，关注行业人才与业务机会。",
      "source": "腾讯新闻",
      "url": "https://so.html5.qq.com/page/real/search_news?docid=70000021_9336a726d2426452"
    },
    {
      "id": 31,
      "cat": "社会/生活",
      "time": "18:38",
      "impact": "low",
      "related": false,
      "overseas": false,
      "title": "国家网信办处置一批涉企侵权账号",
      "summary": "国家网信办从严处置“电车小飞”“职场五斗米”等恶意抹黑诋毁企业、炒作涉企负面信息的违法违规账号。",
      "decision": "涉企网络环境净化利好上市公司声誉，可作为投资情绪面参考。",
      "source": "腾讯新闻",
      "url": "https://so.html5.qq.com/page/real/search_news?docid=70000021_9336a726d2426452"
    },
    {
      "id": 32,
      "cat": "社会/生活",
      "time": "08:05",
      "impact": "low",
      "related": false,
      "overseas": false,
      "title": "邯郸法院执行局长涉骚扰被停职",
      "summary": "河北邯郸一女当事人称被法院执行局长电话索贿、性骚扰，邯郸中院确认录音属实并对其停职处理。",
      "decision": "司法系统违纪个案，关注公职廉洁舆情，不构成立项信号。",
      "source": "扬眼/腾讯",
      "url": "https://new.qq.com/rain/a/20260806A07P1700"
    },
    {
      "id": 33,
      "cat": "娱乐/文娱",
      "time": "11:30",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "周星驰《功夫女足》票房破 22 亿，旧怨争议再起",
      "summary": "《功夫女足》票房突破 22 亿元；李修贤直播嘲讽周星驰后发布道歉视频，网友普遍认为诚意不足。文娱清朗行动持续打击 AI 造谣与饭圈乱象。",
      "decision": "仅作社会文化观察——文娱监管趋严、AI 造谣管控加强，不构成立项或投资信号。",
      "source": "新浪娱乐",
      "url": "https://ent.sina.cn/2026-08-07/detail-inimmpqz3372208.d.html"
    },
    {
      "id": 34,
      "cat": "金融",
      "time": "07:32",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "多家消金公司下调贷款利率上限至 20% 以内，招联上线成本明示",
      "summary": "《个人贷款业务明示综合融资成本规定》落地，南银法巴、盛银、阳光等多家消金公司将新增贷款年化利率上限从 24% 下调至 20%；招联 8 月 1 日上线综合融资成本明示功能。",
      "decision": "利率下行 + 息费透明化是招联所在行业的核心变量，直接影响定价与合规成本，必须纳入专项周报重点跟踪。",
      "source": "金融界/腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260807A0667A00"
    },
    {
      "id": 35,
      "cat": "金融",
      "time": "08:12",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "消费金融公司发展报告 2026：4 家试点贴息贷款超 400 亿",
      "summary": "银行业协会报告显示，蚂蚁消金、招联消金、兴业消金、中银消金入选首批经办机构，累计服务客户超 1500 万人次，发放贴息贷款超 400 亿元；行业总资产 1.48 万亿，科技投入向“数智化”迭代。",
      "decision": "财政贴息 + 金融支持扩消费，招联作为首批机构直接受益，关注贴息规模与客群扩张对业绩的拉动。",
      "source": "中国银行保险报",
      "url": "https://www.toutiao.com/article/7670333496115642926"
    },
    {
      "id": 36,
      "cat": "金融",
      "time": "10:21",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "个贷息费明示新规 8 月 1 日落地，助贷模式系统性重构",
      "summary": "新规将贷款利息、分期费、增信服务费、逾期罚息等全部纳入综合融资成本并标准化披露；业内称助贷平台收费模式面临系统性重构，从流量变现转向真实价值服务。",
      "decision": "助贷生态重构将改变获客与分润结构，招联自营风控与合规披露能力是护城河，建议关注合作方调整。",
      "source": "财联社",
      "url": "https://www.toutiao.com/article/7668882541348225555"
    },
    {
      "id": 37,
      "cat": "金融",
      "time": "18:04",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "金融机构智能体招标升温，兴业消金等“四箭齐发”",
      "summary": "银行业 AI 预算优先投向信贷与营销获客；兴业消费金融连发数据中台及智能问数、标签挖掘/审查辅助智能体；中信建投财富 AI Agent 推进第四期，国元证券建知识治理智能体。",
      "decision": "金融智能体从“轻量订阅”走向“平台自建”，反映行业数字化投入方向，招联可对标同业智能体布局。",
      "source": "新浪财经",
      "url": "https://finance.sina.com.cn/stock/relnews/cn/2026-08-04/doc-inimcpim5763237.shtml"
    },
    {
      "id": 38,
      "cat": "金融",
      "time": "18:06",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "中信建投财富 AI Agent 第四期；国元证券知识治理智能体中标",
      "summary": "中信建投证券财富 AI Agent 2026 项目推进至第四期；国元证券知识治理及智驱工程项目由恒生电子中标，围绕知识治理与多轮深度研究智能问答展开。",
      "decision": "财富管理智能化是券商标配，关注恒生电子等金融 IT 供应商的机会。",
      "source": "新浪财经",
      "url": "https://finance.sina.com.cn/stock/relnews/cn/2026-08-04/doc-inimcpim5763237.shtml"
    },
    {
      "id": 39,
      "cat": "金融",
      "time": "08:10",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "海尔、中银等推行差异化梯度定价，提前还款规则明确",
      "summary": "海尔消金区分贷款模式设置差异化利率（3.2%—24%）；中银消金三大自营产品全面单利计息、梯度定价，部分产品提前还款收 1%—3% 违约金并公示。",
      "decision": "梯度定价 + 透明规则成行业标配，关注其对客群分层与不良率的长期影响。",
      "source": "腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260807A0667A00"
    },
    {
      "id": 40,
      "cat": "金融",
      "time": "18:08",
      "impact": "low",
      "related": false,
      "overseas": false,
      "title": "长城人寿采购智能代码助手与终端助手",
      "summary": "保险领域观察到长城人寿采购智能代码助手及智能终端助手，支持需求理解、任务拆解、跨文件上下文与沙箱操作。",
      "decision": "AI 渗透至保险IT与运营，关注保险科技对人力成本的替代趋势。",
      "source": "新浪财经",
      "url": "https://finance.sina.com.cn/stock/relnews/cn/2026-08-04/doc-inimcpim5763237.shtml"
    },
    {
      "id": 41,
      "cat": "金融",
      "time": "08:15",
      "impact": "low",
      "related": false,
      "overseas": false,
      "title": "建信消金利率 5.68%—23.6%；小米消金维持 24% 上限",
      "summary": "据统计，建信消费金融综合年化利率区间 5.68%—23.6%；中邮、小米等机构现阶段利率上限维持 24%，行业分化明显。",
      "decision": "头部机构利率分化反映客群与资金成本差异，可作为同业对标参考。",
      "source": "腾讯新闻",
      "url": "https://new.qq.com/rain/a/20260807A0667A00"
    },
    {
      "id": 42,
      "cat": "AI行业",
      "time": "08:05",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "字节发布音视频全双工大模型 SeedRealtime，豆包全量上线",
      "summary": "字节跳动推出原生音视频全双工大模型 SeedRealtime，统一架构融合音频、视频与文本，实现“边看边听边说”实时交互，已在豆包 App 全量上线。",
      "decision": "全模态交互是下一代入口争夺点，关注字节多模态对联通/腾讯智能体路线的竞争压力。",
      "source": "i黑马",
      "url": "https://www.163.com/dy/article/L3JVB3LV05118I96.html"
    },
    {
      "id": 43,
      "cat": "AI行业",
      "time": "08:06",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "DeepSeek 重启第二轮融资，拟募资 500 亿、估值 5000 亿",
      "summary": "据《财经》报道，DeepSeek 已重启第二轮融资，计划募资 500 亿元、投前估值约 5000 亿元，预计 8 月下旬签约；若落地两轮累计募资超 1000 亿。",
      "decision": "国产大模型资本与估值双爆发，关注对算力需求与 AI 应用生态的拉动。",
      "source": "南方都市报",
      "url": "https://www.toutiao.com/article/7670489467597226511/"
    },
    {
      "id": 44,
      "cat": "AI行业",
      "time": "08:03",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "阿里发布 2.4 万亿参数千问 3.8-Max，全球榜单第二",
      "summary": "阿里巴巴发布千问系列最大模型 Qwen3.8-Max，总参数 2.4 万亿、激活 950 亿，Arena 榜单仅次于 Claude 系列居全球第二；权重及 27B 版本将开源。",
      "decision": "国产旗舰模型逼近国际闭源，利好国内 AI 应用与算力需求，关注阿里云生态机会。",
      "source": "智东西/北京日报",
      "url": "https://www.toutiao.com/article/7670489467597226511/"
    },
    {
      "id": 45,
      "cat": "AI行业",
      "time": "07:31",
      "impact": "high",
      "related": false,
      "overseas": false,
      "title": "Kimi K3 2.8 万亿参数登顶 Frontend Code Arena",
      "summary": "月之暗面 Kimi K3 总参数 2.8 万亿，以 1679 分登顶 Frontend Code Arena，首次实现开源模型在前端编程榜单超越 Claude、GPT 等闭源模型，具备原生多模态。",
      "decision": "国产开源模型编程能力突围，关注对开发者生态与coding工具链的影响。",
      "source": "南方都市报",
      "url": "https://www.toutiao.com/article/7670489467597226511/"
    },
    {
      "id": 46,
      "cat": "AI行业",
      "time": "07:31",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "MiniMax H3 视频模型发布，0.8 元/秒仅为旗舰 1/3",
      "summary": "MiniMax 发布第三代视频模型 H3，价格 0.8 元/秒（2K），为业内同类旗舰三分之一；架构统一多模态上下文理解创作意图。",
      "decision": "视频生成价格“斩杀线”压低内容创作门槛，关注 AIGC 商业化与版权合规。",
      "source": "南方都市报",
      "url": "https://www.toutiao.com/article/7670489467597226511/"
    },
    {
      "id": 47,
      "cat": "AI行业",
      "time": "08:04",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "腾讯混元发布 Hy ASR 3.0 语音识别模型",
      "summary": "腾讯混元正式发布新一代语音识别模型 Hy ASR 3.0 preview，强化中文语音理解与实时转写能力。",
      "decision": "语音模型是智能体与车载/客服场景底座，关注腾讯混元在联通合作中的可集成性。",
      "source": "i黑马",
      "url": "https://www.163.com/dy/article/L3JVB3LV05118I96.html"
    },
    {
      "id": 48,
      "cat": "AI行业",
      "time": "08:03",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "阿里“千问办公”Agent 公测，接入钉钉",
      "summary": "阿里整合 QoderWork、MuleRun、悟空推出企业级 Agent“千问办公”并公测，由 Qwen3.8 深度绑定，初步打通钉钉 IM。",
      "decision": "AI to B 战略提速，关注企业级 Agent 对招联内部办公与客服提效的借鉴。",
      "source": "北京商报",
      "url": "https://new.qq.com/rain/a/20260803A06OHV00"
    },
    {
      "id": 49,
      "cat": "AI行业",
      "time": "08:03",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "特斯拉中国车机接入豆包大模型",
      "summary": "特斯拉中国推送 2026.14.13 车机更新，首次在国内搭载字节豆包大模型承担车载智能助手；阿里千问亦进入深度测试。",
      "decision": "国产大模型“上车”竞赛加剧，关注车联网与智能座舱对通信网络的增量需求。",
      "source": "央广网",
      "url": "https://new.qq.com/rain/a/20260804A0AMRC00"
    },
    {
      "id": 50,
      "cat": "AI行业",
      "time": "08:07",
      "impact": "mid",
      "related": false,
      "overseas": false,
      "title": "中国模型集体出击，美媒称美国同行面临“死亡地带”",
      "summary": "Kimi K3、阿里千问 3.8、DeepSeek-V4-Flash、字节 Seedance 2.5 密集落地，美媒称中国模型在价格与能力上对美国同行形成压制。",
      "decision": "中美 AI 实力此消彼长，关注国产替代与出口管制博弈对算力链的双向影响。",
      "source": "北京日报",
      "url": "https://xinwen.bjd.com.cn/content/s6a734a1fe4b03fa51a828a53.html"
    },
    {
      "id": 51,
      "cat": "AI行业",
      "time": "08:07",
      "impact": "high",
      "related": false,
      "overseas": true,
      "title": "[海外] OpenAI 发布 GPT-5.6，免费用户文字不限 + “思考”按键",
      "summary": "OpenAI 宣布 GPT-5.6 系列：免费用户默认 Luna 模型、文字互动不再受限，并新增“思考”按键与计算强度滑块；事实准确率较 5.5 显著提升。",
      "decision": "国际旗舰模型加速免费与降本，倒逼国产模型价格战；关注对国内应用层的成本红利。",
      "source": "新浪财经(转 OpenAI)",
      "url": "https://cj.sina.com.cn/article/norm_detail?url=https%3A%2F%2Ffinance.sina.com.cn%2Fstock%2Fwbstock%2F2026-08-07%2Fdoc-inimnkum3274300.shtml"
    },
    {
      "id": 52,
      "cat": "AI行业",
      "time": "08:00",
      "impact": "high",
      "related": false,
      "overseas": true,
      "title": "[海外] Anthropic 发布 Sonnet 5 与 Opus 4.8，强化编程与长任务",
      "summary": "Anthropic 发布 Sonnet 5（最强 agentic 编程与专业工作）与 Opus 4.8（长时程任务一致性升级），并扩展 Project Glasswing 至 150+ 组织。",
      "decision": "国际闭源旗舰持续迭代，是国内模型的对标锚点；关注其安全与 agentic 能力对行业标准的塑造。",
      "source": "Anthropic",
      "url": "https://www.anthropic.com"
    },
    {
      "id": 901,
      "cat": "母婴",
      "time": "09:00",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "2026年度育儿补贴已发放2516万人，首次申请截止延长至年底",
      "summary": "国家卫健委、财政部将2022—2024年出生婴幼儿的首次育儿补贴申请截止时间延长至2026年12月31日；截至当前2026年度已发放2516万人，基础标准每孩每年3600元至3周岁。",
      "decision": "宝宝预产期8/25，记得在出生当月通过支付宝/微信/政务平台‘育儿补贴专区’申领，每年3600元、连发3年，别错过首次申请窗口。",
      "source": "中国政府网",
      "url": "https://www.gov.cn/lianbo/202607/content_7076240.htm"
    },
    {
      "id": 902,
      "cat": "母婴",
      "time": "10:20",
      "impact": "high",
      "related": true,
      "overseas": false,
      "title": "生育津贴基本实现直发个人账户，3岁以下个税专项扣除每月2000元",
      "summary": "自2026年起生育津贴基本直接打到个人账户、跳过单位中转；照护3岁以下婴幼儿每月可享2000元个税专项附加扣除，父母可选一方全额或双方各半。",
      "decision": "生育津贴直发+个税每月省2000元，直接增厚家庭现金流；配偶陪产假约15天、每年育儿假各10天，提前规划产假期间工作交接。",
      "source": "央视新闻",
      "url": "https://www.zydey.com.cn/department_szyxka0_ksdt/2026/Xe02G7bx.html"
    },
    {
      "id": 903,
      "cat": "母婴",
      "time": "11:05",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "无痛分娩已纳入30省份医保，辅助生殖报销比例60%—85%",
      "summary": "全国30省份将分娩镇痛纳入医保，深圳等地可100%报销；辅助生殖取卵术、胚胎培养等8—13个项目纳入医保，职工医保报销60%—85%。",
      "decision": "分娩镇痛/辅助生殖进医保，预计人均减负超千元；若考虑无痛分娩，提前确认就诊医院是否在报销范围内。",
      "source": "健康上海12320",
      "url": "https://www.zydey.com.cn/department_szyxka0_ksdt/2026/Xe02G7bx.html"
    },
    {
      "id": 904,
      "cat": "母婴",
      "time": "11:40",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "南充出台稳定新出生人口‘六条措施’：生育慰问+消费/汽车补助",
      "summary": "南充对一/二/三孩分别给予最高1600/3200/4800元生育慰问；二孩三孩家庭发1000元育儿消费补助，购新乘用车按5%补贴最高2.5万元；设‘生育友好岗’支持弹性办公。",
      "decision": "若户籍或居住地涉及地方补贴，注意孩子出生1年内申请、过期不补；‘生育友好岗’可规划产假后返岗的弹性安排。",
      "source": "南充市政府",
      "url": "https://www.nanchong.gov.cn/zwgk/zfgb/2026n/d2q/202603/t20260318_2319635.html"
    },
    {
      "id": 905,
      "cat": "母婴",
      "time": "12:10",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "闽清生育友好新政：住院分娩费用全免、三孩一次性发1万元",
      "summary": "闽清县规定福州定点医院住院分娩医保范围内费用全免；2026年后出生三孩一次性发1万元；普惠托育每人每月补贴150—300元，三孩家庭公租房5年租金减免。",
      "decision": "地方生育补贴力度加大，可对照户籍地政策查漏补缺；托育补贴显著降低0—3岁养育成本，提前了解就近普惠托育点。",
      "source": "央广网",
      "url": "https://baijiahao.baidu.com/s?id=1862593156438313560"
    },
    {
      "id": 906,
      "cat": "母婴",
      "time": "13:30",
      "impact": "mid",
      "related": true,
      "overseas": false,
      "title": "普惠托育扩容：全国托位数666万，2026年再增15万普惠托位",
      "summary": "全国托育机构超12.6万家、托位数666万个，2026年再增15万普惠托位，全日托均价降29%；大型场所母婴室须不小于10平米独立室。",
      "decision": "产假结束后托育是刚需，普惠托位扩容量价齐降是利好；可提前锁定居住地附近普惠托育资源，关注母婴室覆盖。",
      "source": "央视新闻",
      "url": "https://www.zydey.com.cn/department_szyxka0_ksdt/2026/Xe02G7bx.html"
    },
    {
      "id": 907,
      "cat": "母婴",
      "time": "14:00",
      "impact": "low",
      "related": true,
      "overseas": false,
      "title": "母婴消费提示：奶粉/纸尿裤选国产vs进口、安全座椅认准3C/i-Size",
      "summary": "国产奶粉质量持续提升、性价比高；安全座椅在多地已纳入上车强制要求，选购需看3C与i-Size认证；建议关注大促节点按需囤刚需品。",
      "decision": "结合家庭财务，奶粉/纸尿裤按宝宝月龄分批囤、避免一次性过度囤货；安全座椅认准3C/i-Size，别为省钱牺牲安全。",
      "source": "消费提示(综合)",
      "url": "https://www.gov.cn/lianbo/202607/content_7076240.htm"
    },
    {
      "id": 908,
      "cat": "母婴",
      "time": "14:30",
      "impact": "low",
      "related": true,
      "overseas": false,
      "title": "早教与亲子：0—3岁启蒙以互动为主，警惕‘超前教育’营销",
      "summary": "专家提示0—3岁以语言、运动、情感互动式启蒙为主，无需过早学科培训；警惕以‘神童’‘超前’为噱头的高价课程营销。",
      "decision": "早教重在陪伴而非砸钱，预算优先放在安全与健康刚需；遇高价‘超前教育’课程先核实资质再决定。",
      "source": "育儿科普(综合)",
      "url": "https://www.zydey.com.cn/department_szyxka0_ksdt/2026/Xe02G7bx.html"
    }
  ]
};
